// Generated by the Ballerina OpenAPI tool from
// specs/design/components/todo-api/openapi.yaml, then filled in: the
// listener binds on all interfaces, the service became interceptable so the
// gateway's signed assertion is verified on every request (gateway_assertion.bal),
// and every resource resolves the caller from that assertion instead of
// trusting anything the client sent.
import ballerina/http;
import ballerina/time;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # Delete the caller's own entry
    #
    # + return - returns can be any of following types
    # http:NoContent (Deleted)
    # http:Unauthorized (Not signed in)
    # http:NotFound (No such entry for this caller)
    resource function delete me/todo\-entries/[string entryId](http:RequestContext ctx)
            returns http:NoContent|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        boolean deleted = check deleteTodoEntry(entryId, caller.userId);
        if !deleted {
            // Either it never existed, or it belongs to someone else — both
            // answer 404, never 403, so a caller cannot learn a row exists
            // by probing it.
            return notFoundError();
        }
        return http:NO_CONTENT;
    }

    # The caller's to-do entries
    resource function get me/todo\-entries(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        int pageLimit = 'limit < 1 ? 20 : ('limit > 100 ? 100 : 'limit);
        int pageOffset = offset < 0 ? 0 : offset;
        TodoEntryDbRow[] rows = check listTodoEntries(caller.userId, pageLimit, pageOffset);
        int total = check countTodoEntries(caller.userId);
        TodoEntry[] data = from TodoEntryDbRow row in rows select toTodoEntry(row);
        string? next = (pageOffset + pageLimit) < total
            ? string `/me/todo-entries?limit=${pageLimit}&offset=${pageOffset + pageLimit}`
            : ();
        int previousOffset = pageOffset - pageLimit;
        string? previous = pageOffset > 0
            ? string `/me/todo-entries?limit=${pageLimit}&offset=${previousOffset < 0 ? 0 : previousOffset}`
            : ();
        return {count: total, next, previous, data};
    }

    # Edit or complete/uncomplete the caller's own entry
    #
    # + return - returns can be any of following types
    # http:Ok (The updated entry)
    # http:BadRequest (Invalid update)
    # http:Unauthorized (Not signed in)
    # http:NotFound (No such entry for this caller)
    resource function patch me/todo\-entries/[string entryId](http:RequestContext ctx, @http:Payload TodoEntryUpdate payload)
            returns TodoEntry|ErrorBadRequest|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        string? rawTitle = payload?.title;
        if rawTitle is string && rawTitle.trim() == "" {
            return badRequestError("title must not be empty");
        }
        string? newTitle = rawTitle is string ? rawTitle.trim() : ();
        boolean? newDone = payload?.done;
        TodoEntryDbRow? updated = check updateTodoEntry(entryId, caller.userId, newTitle, newDone);
        if updated is () {
            return notFoundError();
        }
        return toTodoEntry(updated);
    }

    resource function post me/todo\-entries(http:RequestContext ctx, @http:Payload TodoEntryCreate payload)
            returns TodoEntry|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        string title = payload.title.trim();
        if title == "" {
            return badRequestError("title must not be empty");
        }
        TodoEntryDbRow created = check insertTodoEntry(caller.userId, title);
        return toTodoEntry(created);
    }
}

isolated function unauthorizedError() returns ErrorUnauthorized => {
    body: {code: 401, message: "not signed in"}
};

isolated function notFoundError() returns ErrorNotFound => {
    body: {code: 404, message: "no such entry for this caller"}
};

isolated function badRequestError(string message) returns ErrorBadRequest => {
    body: {code: 400, message}
};

isolated function toTodoEntry(TodoEntryDbRow row) returns TodoEntry => {
    id: row.id,
    title: row.title,
    done: row.done,
    createdAt: time:utcToString(row.createdAt),
    updatedAt: time:utcToString(row.updatedAt)
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type TodoEntryUpdate record {
    # new title
    string title?;
    # new completion state
    boolean done?;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    TodoEntry[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type TodoEntry record {
    # entry id
    string id;
    # entry title
    string title;
    # completion state
    boolean done;
    string createdAt;
    string updatedAt;
};

public type TodoEntryCreate record {
    # entry title
    string title;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
